artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1I1xw3I6UIPyFkGa8zvO5yM1oP2F_ifqt/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/training 
  trained_model_path: artifacts/training/model.h5

evaluation:
  mlflow_uri: https://dagshub.com/vivek34561/kidney_disease_classification.mlflow  